name = "green41_double_exponential_lean4web"
version = "0.1.0"
defaultTargets = ["Green41DoubleExponentialLean4Web"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "5e0c4e5239cb0a2d86d68a884bf52cfd963fce22"

[[lean_lib]]
name = "Green41DoubleExponentialLean4Web"
